name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Intall 
        run: npm install
      - name: Build
        run: npm run build:prod
      - name: Deploy
        run: npm run deploy